### ISSUE TITLE
Irene error: 'IndexError: Out of bounds on buffer access (axis 0)'

### ISSUE THREAD

**Issue by jmbenlloch** [next-exp/IC#175]
@jahernando asked me to run Irene over Na data (run 2948 from last campaign). @gonzaponte send me a set of parameters to do so. This is the configuration file:

```
PATH_IN /analysis/2948/hdf5/data
PATH_OUT /analysis/2948/hdf5/irene
FILE_IN run_2948.gdc*next.001.next1el_2948.root.h5
FILE_OUT run_2948.gdcsnext.001.next1el_2948.root.h5
COMPRESSION ZLIB4

RUN_NUMBER 2948

NPRINT 100
PRINT_EMPTY_EVENTS 1

## JJ
NBASELINE 38000
THR_TRIGGER 5

## JJ
NMAU 100
THR_MAU 3

## JJ
THR_CSUM_S1 0.2
THR_CSUM_S2 1.0

## JJ
NMAU_SIPM 100
THR_SIPM 3.5

S1_TMIN 99
S1_TMAX 101
S1_STRIDE 4
S1_LMIN 4
S1_LMAX 16

S2_TMIN 101
S2_TMAX 1200
S2_STRIDE 40
S2_LMIN 60
S2_LMAX 100000

THR_SIPM_S2 20

NEVENTS 0
RUN_ALL True
```

Data files can be copied from Canfranc or from here:
https://www.cern.ch/jobenllo/run_2948.gdc1next.001.next1el_2948.root.h5
https://www.cern.ch/jobenllo/run_2948.gdc2next.001.next1el_2948.root.h5

This is the error I'm getting:

```
$ python $ICDIR/cities/irene.py -c /home/jmbenlloch/productions/configs_new//irene_r2948_1.conf
COMPRESSION            => ZLIB4
FILE_IN                => /analysis/2948/hdf5/data/run_2948.gdc*next.001.next1el_2948.root.h5
FILE_OUT               => /analysis/2948/hdf5/irene/run_2948.gdcsnext.001.next1el_2948.root.h5
INFO                   => False
NBASELINE              => 38000
NEVENTS                => 0
NMAU                   => 100
NMAU_SIPM              => 100
NPRINT                 => 100
PATH_IN                => /analysis/2948/hdf5/data
PATH_OUT               => /analysis/2948/hdf5/irene
PRINT_EMPTY_EVENTS     => 1
RUN_ALL                => True
RUN_NUMBER             => 2948
S1_LMAX                => 16
S1_LMIN                => 4
S1_STRIDE              => 4
S1_TMAX                => 101
S1_TMIN                => 99
S2_LMAX                => 100000
S2_LMIN                => 60
S2_STRIDE              => 40
S2_TMAX                => 1200
S2_TMIN                => 101
SKIP                   => 0
THR_CSUM_S1            => 0.2
THR_CSUM_S2            => 1.0
THR_MAU                => 3
THR_SIPM               => 3.5
THR_SIPM_S2            => 20
THR_TRIGGER            => 5
VERBOSITY              => 20

                 Irene will run a max of -1 events
                 Input Files = ['/analysis/2948/hdf5/data/run_2948.gdc1next.001.next1el_2948.root.h5', '/analysis/2948/hdf5/data/run_2948.gdc2next.001.next1el_2948.root.h5']
                 Output File = /analysis/2948/hdf5/irene/run_2948.gdcsnext.001.next1el_2948.root.h5
                          

                 S1 parameters S12Params(tmin=99000.0, tmax=101000.0, stride=4, lmin=4, lmax=16, rebin=False)

                 S2 parameters S12Params(tmin=101000.0, tmax=1200000.0, stride=40, lmin=60, lmax=100000, rebin=True)

                 S2Si parameters
                 threshold min charge per SiPM = 3.5 pes
                 threshold min charge in  S2   = 20 pes
                          
Opening /analysis/2948/hdf5/data/run_2948.gdc1next.001.next1el_2948.root.h5... Events in file = 132
# PMT                  => 12
# SiPM                 => 1792
PMT WL                 => 32000
SIPM WL                => 800
Traceback (most recent call last):
  File "/home/jmbenlloch/IC/invisible_cities/cities/irene.py", line 376, in <module>
    IRENE(sys.argv)
  File "/home/jmbenlloch/IC/invisible_cities/cities/irene.py", line 366, in IRENE
    nevt = irene.run(nmax=nevts, print_empty=CFP.PRINT_EMPTY_EVENTS)
  File "/home/jmbenlloch/IC/invisible_cities/cities/irene.py", line 249, in run
    CWF = self.deconv_pmt(pmtrwf[evt])
  File "/home/jmbenlloch/IC/invisible_cities/cities/base_cities.py", line 319, in deconv_pmt
    thr_trigger = self.thr_trigger)
  File "invisible_cities/sierpe/blr.pyx", line 91, in invisible_cities.sierpe.blr.deconv_pmt (invisible_cities/sierpe/blr.c:3912)
  File "invisible_cities/sierpe/blr.pyx", line 108, in invisible_cities.sierpe.blr.deconv_pmt (invisible_cities/sierpe/blr.c:3667)
  File "invisible_cities/sierpe/blr.pyx", line 38, in invisible_cities.sierpe.blr.deconvolve_signal (invisible_cities/sierpe/blr.c:2430)
IndexError: Out of bounds on buffer access (axis 0)
```

Any idea?

**Comment by gonzaponte** [comment]
It is probably this:
PMT WL                 => 32000
NBASELINE              => 38000

Set NBASELINE 28000 and try again

**Comment by jmbenlloch** [comment]
Ok, it's working now. Thanks!

**Comment by jjgomezcadenas** [comment]
Are u sure that the buffer is 38000 long? I suspect is shorter for this run…
