### ISSUE TITLE
counters bug running dorothea with corona

### ISSUE THREAD

**Issue by abotas** [next-exp/IC#347]
There is a counter `n_events_more_than_1_cluster` in `Counter` that is never initialized (i think it is only in one place in the code and we are trying to add 1 to it). 

When I try to run dorothea with corona it crashes immediately. 
I think this is a simple fix, but I don't know if this is a counter we care about or if we should just get rid of it? @gonzaponte @jjgomezcadenas 

```
event in file = 0, total = 0
Traceback (most recent call last):
  File "/software/IC-dev//bin/city", line 19, in <module>
    city_class.drive(args)
  File "/software/IC-dev/invisible_cities/cities/base_cities.py", line 187, in drive
    instance.go()
  File "/software/IC-dev/invisible_cities/cities/base_cities.py", line 196, in go
    self.run()
  File "/software/IC-dev/invisible_cities/cities/base_cities.py", line 219, in run
    self.file_loop()
  File "/software/IC-dev/invisible_cities/cities/base_cities.py", line 716, in file_loop
    self.event_loop(pmapVectors)
  File "/software/IC-dev/invisible_cities/cities/base_cities.py", line 690, in event_loop
    evt = self.create_dst_event(pmapVectors)
  File "/software/IC-dev/invisible_cities/cities/dorothea.py", line 24, in create_dst_event
    return  self.create_kr_event(pmapVectors)
  File "/software/IC-dev/invisible_cities/cities/base_cities.py", line 826, in create_kr_event
    self.cnt.n_events_more_than_1_cluster += 1
AttributeError: 'Counters' object has no attribute 'n_events_more_than_1_cluster'
```

**Comment by gonzaponte** [comment]
It is not harmful to have it.
