### ISSUE TITLE
strange problem when trying to run source manage.sh work_in_py...

### ISSUE THREAD

**Issue by abotas** [next-exp/IC#378]
When I run
`source manage.sh work_in_python_version 3.6`
 I get a strange error:
```
Traceback (most recent call last):
  File "/Users/alej/miniconda/envs/IC3.6/lib/python3.6/site-packages/_pytest/config.py", line 325, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/Users/alej/Desktop/Valencia/nextic/IC-1')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/alej/miniconda/envs/IC3.6/lib/python3.6/site-packages/_pytest/config.py", line 356, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/Users/alej/Desktop/Valencia/nextic/IC-1/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/alej/miniconda/envs/IC3.6/lib/python3.6/site-packages/_pytest/config.py", line 362, in _importconftest
    mod = conftestpath.pyimport()
  File "/Users/alej/miniconda/envs/IC3.6/lib/python3.6/site-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/alej/miniconda/envs/IC3.6/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 216, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/Users/alej/Desktop/Valencia/nextic/IC-1/conftest.py", line 9, in <module>
    settings.register_profile("hard_nocov", settings(max_examples = 1000, use_coverage=False))
  File "/Users/alej/miniconda/envs/IC3.6/lib/python3.6/site-packages/hypothesis/_settings.py", line 151, in __init__
    'Invalid argument %s' % (name,))
hypothesis.errors.InvalidArgument: Invalid argument use_coverage
ERROR: could not load /Users/alej/Desktop/Valencia/nextic/IC-1/conftest.py
```

I think this first occurred after I rebased a branch of mine on top of master. I tried all the initial stuff I always try (compiling, cleaning, dowloading the db etc) but none of it worked. Eventually i deleted / recloned everything and did a new `install_and_check` and it the problem disappeared.

But a few hours later it reappeared after checking out an old branch, so i figured I should post the issue here just in case someone has any ideas. It looks like it has to do with hypothesis.

**Comment by jacg** [comment]
`use_coverage` is a setting that was added to hypothesis itself in 3.29 (about 4 weeks ago). Its use in a `conftest.py` appeared on `nextic/master` 6 days ago. That part of the problem should go away if you ensure that you have a version of hypothesis >= 3.29.

**Comment by abotas** [comment]
ok completely resolved, closing the issue
